---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
        - build-essential
        - docker-compose

    - name:    Install Docker prerequisites
      apt:     name={{item}} update_cache=yes
      with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
    - name:    Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name:    Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge

    - name:    Install Docker
      apt:     name=docker-ce

    - name: Install DSP
      git: 
        repo: https://github.com/giper45/DockerSecurityPlayground.git
        dest: /home/vagrant/DockerSecurityPlayground
    # - name: add repository and install its signing key
    #   shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -

    # - name: Install nodejs
    #   apt: name=nodejs update_cache=yes


